
-- -----------------------------------------------------------------------------
--m_downsynctabledetail - what to down-sync, in what order, and how
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS db_iemr.m_downsynctabledetail (
    DownSyncTableDetailID INT           NOT NULL AUTO_INCREMENT,
    SchemaName            VARCHAR(100)  NOT NULL COMMENT 'db_identity / db_iemr',
    TableName             VARCHAR(200)  NOT NULL COMMENT 'table to down-sync',
    ServerColumnName      TEXT          NULL     COMMENT 'columns to SELECT from central; NULL = resolve from information_schema',
    VanColumnName         TEXT          NULL     COMMENT 'columns in local, positionally mapped with ServerColumnName',
    VanAutoIncColumnName  VARCHAR(200)  NULL     COMMENT 'primary key column',
    TableType             VARCHAR(20)   NOT NULL DEFAULT 'MASTER' COMMENT 'MASTER = full pull, no VanID filter / TRANSACTIONAL = filter by VanID + DownSynced',
    SyncOrder             INT           NOT NULL DEFAULT 1000 COMMENT 'lower number syncs first - enforces the FK dependency chain',
    IsActive              BIT(1)        NOT NULL DEFAULT b'1',
    FkColumnMapping       TEXT          NULL     COMMENT 'childColumn:schema.parentTable, ; separated - columns holding a parent primary key that differs between central and the van',
    PreserveCentralPK     BIT(1)        NOT NULL DEFAULT b'0' COMMENT 'key is allocated centrally - insert it as it arrives instead of re-minting',
    Deleted               BIT(1)        NOT NULL DEFAULT b'0',
    CreatedBy             VARCHAR(50)   NULL,
    CreatedDate           DATETIME      NULL     DEFAULT CURRENT_TIMESTAMP,
    ModifiedBy            VARCHAR(50)   NULL,
    LastModDate           DATETIME      NULL     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (DownSyncTableDetailID),
    UNIQUE KEY uk_downsynctabledetail_table (SchemaName, TableName),
    KEY idx_downsynctabledetail_order (SyncOrder)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

INSERT INTO db_iemr.m_downsynctabledetail
    (SchemaName, TableName, VanAutoIncColumnName, TableType, SyncOrder, IsActive,
     FkColumnMapping, PreserveCentralPK)
VALUES
    ('db_identity', 'm_beneficiaryregidmapping', 'BenRegId', 'TRANSACTIONAL', 0, b'1', NULL, b'1'),
    ('db_identity', 'i_beneficiarydetails', 'BeneficiaryDetailsId', 'TRANSACTIONAL', 1, b'1', NULL, b'0'),
    ('db_identity', 'i_beneficiaryaddress', 'BenAddressID', 'TRANSACTIONAL', 2, b'1', NULL, b'0'),
    ('db_identity', 'i_beneficiarycontacts', 'BenContactsID', 'TRANSACTIONAL', 3, b'1', NULL, b'0'),
    ('db_identity', 'i_beneficiaryaccount', 'BenAccountID', 'TRANSACTIONAL', 4, b'1', NULL, b'0'),
    ('db_identity', 'i_beneficiaryconsent', 'BenConsentId', 'TRANSACTIONAL', 4, b'0', NULL, b'0'),
    ('db_identity', 'i_beneficiaryimage', 'BenImageId', 'TRANSACTIONAL', 4, b'1', NULL, b'0'),
    ('db_identity', 'i_beneficiarymapping', 'BenMapId', 'TRANSACTIONAL', 5, b'1', 'BenDetailsId:db_identity.i_beneficiarydetails;BenAddressId:db_identity.i_beneficiaryaddress;BenContactsId:db_identity.i_beneficiarycontacts;BenAccountID:db_identity.i_beneficiaryaccount;BenImageId:db_identity.i_beneficiaryimage', b'0'),
    ('db_identity', 'i_beneficiaryfamilymapping', 'BenFamilyMapId', 'TRANSACTIONAL', 6, b'1', 'BenMapId:db_identity.i_beneficiarymapping', b'0'),
    ('db_identity', 'i_beneficiaryidentity', 'BenIdentityId', 'TRANSACTIONAL', 7, b'1', 'BenMapId:db_identity.i_beneficiarymapping', b'0'),
    ('db_iemr', 't_benvisitdetail', 'BenVisitID', 'TRANSACTIONAL', 9, b'1', NULL, b'0'),
    ('db_iemr', 't_phy_anthropometry', 'ID', 'TRANSACTIONAL', 10, b'1', NULL, b'0'),
    ('db_iemr', 't_phy_vitals', 'ID', 'TRANSACTIONAL', 11, b'1', NULL, b'0'),
    ('db_iemr', 't_benadherence', 'ID', 'TRANSACTIONAL', 12, b'1', NULL, b'0'),
    ('db_iemr', 't_anccare', 'ID', 'TRANSACTIONAL', 13, b'1', NULL, b'0'),
    ('db_iemr', 't_pnccare', 'ID', 'TRANSACTIONAL', 14, b'1', NULL, b'0'),
    ('db_iemr', 't_ncdscreening', 'ID', 'TRANSACTIONAL', 15, b'1', NULL, b'0'),
    ('db_iemr', 't_ncdcare', 'ID', 'TRANSACTIONAL', 16, b'1', NULL, b'0'),
    ('db_iemr', 't_phy_generalexam', 'ID', 'TRANSACTIONAL', 17, b'1', NULL, b'0'),
    ('db_iemr', 't_phy_headtotoe', 'ID', 'TRANSACTIONAL', 18, b'1', NULL, b'0'),
    ('db_iemr', 't_sys_obstetric', 'ID', 'TRANSACTIONAL', 19, b'1', NULL, b'0'),
    ('db_iemr', 't_sys_gastrointestinal', 'ID', 'TRANSACTIONAL', 20, b'1', NULL, b'0'),
    ('db_iemr', 't_sys_cardiovascular', 'ID', 'TRANSACTIONAL', 21, b'1', NULL, b'0'),
    ('db_iemr', 't_sys_respiratory', 'ID', 'TRANSACTIONAL', 22, b'1', NULL, b'0'),
    ('db_iemr', 't_sys_centralnervous', 'ID', 'TRANSACTIONAL', 23, b'1', NULL, b'0'),
    ('db_iemr', 't_sys_musculoskeletalsystem', 'ID', 'TRANSACTIONAL', 24, b'1', NULL, b'0'),
    ('db_iemr', 't_sys_genitourinarysystem', 'ID', 'TRANSACTIONAL', 25, b'1', NULL, b'0'),
    ('db_iemr', 't_ancdiagnosis', 'ID', 'TRANSACTIONAL', 26, b'1', NULL, b'0'),
    ('db_iemr', 't_ncddiagnosis', 'ID', 'TRANSACTIONAL', 27, b'1', NULL, b'0'),
    ('db_iemr', 't_pncdiagnosis', 'ID', 'TRANSACTIONAL', 28, b'1', NULL, b'0'),
    ('db_iemr', 't_benchiefcomplaint', 'ID', 'TRANSACTIONAL', 29, b'1', NULL, b'0'),
    ('db_iemr', 't_benclinicalobservation', 'ClinicalObservationID', 'TRANSACTIONAL', 30, b'1', NULL, b'0'),
    ('db_iemr', 't_prescription', 'PrescriptionID', 'TRANSACTIONAL', 31, b'1', NULL, b'0'),
    ('db_iemr', 't_prescribeddrug', 'PrescribedDrugID', 'TRANSACTIONAL', 32, b'1', NULL, b'0'),
    ('db_iemr', 't_lab_testorder', 'ID', 'TRANSACTIONAL', 33, b'1', NULL, b'0'),
    ('db_iemr', 't_benreferdetails', 'benReferID', 'TRANSACTIONAL', 34, b'1', NULL, b'0'),
    ('db_iemr', 't_lab_testresult', 'ID', 'TRANSACTIONAL', 35, b'1', NULL, b'0'),
    ('db_iemr', 't_physicalstockentry', 'PhyEntryID', 'TRANSACTIONAL', 36, b'1', NULL, b'0'),
    ('db_iemr', 't_patientissue', 'PatientIssueID', 'TRANSACTIONAL', 37, b'1', NULL, b'0'),
    ('db_iemr', 't_facilityconsumption', 'ConsumptionID', 'TRANSACTIONAL', 38, b'1', NULL, b'0'),
    ('db_iemr', 't_itemstockentry', 'ItemStockEntryID', 'TRANSACTIONAL', 39, b'1', NULL, b'0'),
    ('db_iemr', 't_itemstockexit', 'ItemStockExitID', 'TRANSACTIONAL', 40, b'1', NULL, b'0'),
    ('db_iemr', 't_benmedhistory', 'BenMedHistoryID', 'TRANSACTIONAL', 41, b'1', NULL, b'0'),
    ('db_iemr', 't_femaleobstetrichistory', 'ObstetricHistoryID', 'TRANSACTIONAL', 42, b'1', NULL, b'0'),
    ('db_iemr', 't_benmenstrualdetails', 'BenMenstrualID', 'TRANSACTIONAL', 43, b'1', NULL, b'0'),
    ('db_iemr', 't_benpersonalhabit', 'BenPersonalHabitID', 'TRANSACTIONAL', 44, b'1', NULL, b'0'),
    ('db_iemr', 't_childvaccinedetail1', 'ID', 'TRANSACTIONAL', 45, b'1', NULL, b'0'),
    ('db_iemr', 't_childvaccinedetail2', 'ID', 'TRANSACTIONAL', 46, b'1', NULL, b'0'),
    ('db_iemr', 't_childoptionalvaccinedetail', 'ID', 'TRANSACTIONAL', 47, b'1', NULL, b'0'),
    ('db_iemr', 't_ancwomenvaccinedetail', 'ID', 'TRANSACTIONAL', 48, b'1', NULL, b'0'),
    ('db_iemr', 't_childfeedinghistory', 'ID', 'TRANSACTIONAL', 49, b'1', NULL, b'0'),
    ('db_iemr', 't_benallergyhistory', 'ID', 'TRANSACTIONAL', 50, b'1', NULL, b'0'),
    ('db_iemr', 't_bencomorbiditycondition', 'ID', 'TRANSACTIONAL', 51, b'1', NULL, b'0'),
    ('db_iemr', 't_benmedicationhistory', 'ID', 'TRANSACTIONAL', 52, b'1', NULL, b'0'),
    ('db_iemr', 't_benfamilyhistory', 'ID', 'TRANSACTIONAL', 53, b'1', NULL, b'0'),
    ('db_iemr', 't_perinatalhistory', 'ID', 'TRANSACTIONAL', 54, b'1', NULL, b'0'),
    ('db_iemr', 't_developmenthistory', 'ID', 'TRANSACTIONAL', 55, b'1', NULL, b'0'),
    ('db_iemr', 't_cancerfamilyhistory', 'ID', 'TRANSACTIONAL', 56, b'1', NULL, b'0'),
    ('db_iemr', 't_cancerpersonalhistory', 'ID', 'TRANSACTIONAL', 57, b'1', NULL, b'0'),
    ('db_iemr', 't_cancerdiethistory', 'ID', 'TRANSACTIONAL', 58, b'1', NULL, b'0'),
    ('db_iemr', 't_cancerobstetrichistory', 'ID', 'TRANSACTIONAL', 59, b'1', NULL, b'0'),
    ('db_iemr', 't_cancervitals', 'ID', 'TRANSACTIONAL', 60, b'1', NULL, b'0'),
    ('db_iemr', 't_cancersignandsymptoms', 'ID', 'TRANSACTIONAL', 61, b'1', NULL, b'0'),
    ('db_iemr', 't_cancerlymphnode', 'ID', 'TRANSACTIONAL', 62, b'1', NULL, b'0'),
    ('db_iemr', 't_canceroralexamination', 'ID', 'TRANSACTIONAL', 63, b'1', NULL, b'0'),
    ('db_iemr', 't_cancerbreastexamination', 'ID', 'TRANSACTIONAL', 64, b'1', NULL, b'0'),
    ('db_iemr', 't_cancerabdominalexamination', 'ID', 'TRANSACTIONAL', 65, b'1', NULL, b'0'),
    ('db_iemr', 't_cancergynecologicalexamination', 'ID', 'TRANSACTIONAL', 66, b'1', NULL, b'0'),
    ('db_iemr', 't_cancerdiagnosis', 'ID', 'TRANSACTIONAL', 67, b'1', NULL, b'0'),
    ('db_iemr', 't_cancerimageannotation', 'ID', 'TRANSACTIONAL', 68, b'1', NULL, b'0'),
    ('db_iemr', 't_stockadjustment', 'StockAdjustmentID', 'TRANSACTIONAL', 70, b'1', NULL, b'0'),
    ('db_iemr', 't_stocktransfer', 'StockTransferID', 'TRANSACTIONAL', 71, b'1', NULL, b'0'),
    ('db_iemr', 't_patientreturn', 'PatientReturnID', 'TRANSACTIONAL', 72, b'1', NULL, b'0'),
    ('db_iemr', 't_indent', 'IndentID', 'TRANSACTIONAL', 73, b'1', NULL, b'0'),
    ('db_iemr', 't_indentissue', 'IndentIssueID', 'TRANSACTIONAL', 74, b'1', NULL, b'0'),
    ('db_iemr', 't_indentorder', 'IndentOrderID', 'TRANSACTIONAL', 75, b'1', NULL, b'0'),
    ('db_iemr', 't_saitemmapping', 'SAItemMapID', 'TRANSACTIONAL', 76, b'1', NULL, b'0'),
    ('db_iemr', 'tb_stoptb_general_opd', 'id', 'TRANSACTIONAL', 77, b'1', NULL, b'0'),
    ('db_iemr', 'tb_stoptb_general_examination', 'id', 'TRANSACTIONAL', 78, b'1', NULL, b'0'),
    ('db_iemr', 'tb_screening', 'id', 'TRANSACTIONAL', 79, b'1', NULL, b'0'),
    ('db_iemr', 'tb_stoptb_diagnostics', 'id', 'TRANSACTIONAL', 80, b'1', NULL, b'0'),
    ('db_iemr', 'tb_suspected', 'id', 'TRANSACTIONAL', 81, b'1', NULL, b'0'),
    ('db_iemr', 'tb_confirmed_cases', 'id', 'TRANSACTIONAL', 82, b'1', NULL, b'0'),
    ('db_iemr', 'tb_diagnostic_order', 'id', 'TRANSACTIONAL', 83, b'0', NULL, b'0'),
    ('db_iemr', 'tb_diagnostic_result', 'id', 'TRANSACTIONAL', 84, b'0', NULL, b'0'),
    ('db_iemr', 'tb_diagnostic_document', 'id', 'TRANSACTIONAL', 85, b'0', NULL, b'0'),
    ('db_identity', 'i_beneficiarydetails_rmnch', 'beneficiaryDetails_RmnchId', 'TRANSACTIONAL', 86, b'1', NULL, b'0'),
    ('db_identity', 'i_bornbirthdeatils', 'BornBirthDeatilsId', 'TRANSACTIONAL', 87, b'1', NULL, b'0'),
    ('db_identity', 'i_householddetails', 'houseHoldDetailsId', 'TRANSACTIONAL', 88, b'1', NULL, b'0'),
    ('db_iemr', 'tb_stoptb_visit', 'id', 'TRANSACTIONAL', 89, b'1', NULL, b'0'),
    ('db_iemr', 't_form_response', 'responseId', 'TRANSACTIONAL', 90, b'1', NULL, b'0'),
    ('db_iemr', 't_section_response', 'sectionResponseId', 'TRANSACTIONAL', 91, b'0', NULL, b'0'),
    ('db_iemr', 't_question_response', 'questionResponseId', 'TRANSACTIONAL', 92, b'0', NULL, b'0')
ON DUPLICATE KEY UPDATE
    VanAutoIncColumnName = VALUES(VanAutoIncColumnName),
    TableType            = VALUES(TableType),
    SyncOrder            = VALUES(SyncOrder),
    IsActive             = VALUES(IsActive),
    FkColumnMapping      = VALUES(FkColumnMapping),
    PreserveCentralPK    = VALUES(PreserveCentralPK);
