USE db_iemr;

-- ============================================================
-- tb_suspected: flag whether a Nikshay ID was generated by AMRIT
--
-- Set by the Stop TB results-CSV import (stopTb/nikshay/importResultsCsv):
--   1    -> the Nikshay portal generated this ID for us (row status
--           "success"), i.e. AMRIT caused the ID to exist
--   0    -> the ID already existed on the portal and we only matched it
--           back onto the beneficiary (row status "skipped"/"failed")
--   NULL -> unknown: rows written before this column existed, or by any
--           other flow. Deliberately left distinct from an explicit 0.
--
-- Lets the programme count IDs actually created by this application:
--   SELECT COUNT(*) FROM tb_suspected WHERE nikshay_created_by_amrit = 1;
-- ============================================================

SET @schema_name = 'db_iemr';
SET @tbl_name = 'tb_suspected';

SET @col_name = 'nikshay_created_by_amrit';
SET @col_exists = 0;
PREPARE chk_col FROM 'SELECT COUNT(*) INTO @col_exists FROM information_schema.columns WHERE table_schema = ? AND table_name = ? AND column_name = ?';
EXECUTE chk_col USING @schema_name, @tbl_name, @col_name;
DEALLOCATE PREPARE chk_col;
SET @sql = IF(@col_exists = 0,
CONCAT('ALTER TABLE ', @tbl_name, ' ADD COLUMN ', @col_name, ' TINYINT(1) NULL DEFAULT NULL'),
CONCAT('SELECT ''', @tbl_name, '.', @col_name, ' already exists''')
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
