USE db_iemr;

-- Step 1: Take backup of existing data
CREATE TABLE if not EXISTS t_hbnc_visit_backup AS SELECT * FROM t_hbnc_visit;

-- Step 2: Drop the existing table
-- DROP TABLE IF EXISTS t_hbnc_visit;

-- Step 3: Create the new table
CREATE TABLE if not EXISTS `t_hbnc_visit` (
   `id` bigint(20) NOT NULL AUTO_INCREMENT,
   `baby_alive` bit(1) DEFAULT NULL,
   `baby_immunization_status` varchar(255) DEFAULT NULL,
   `baby_weight` float DEFAULT NULL,
   `ben_id` bigint(20) DEFAULT NULL,
   `created_by` varchar(255) DEFAULT NULL,
   `created_date` datetime DEFAULT NULL,
   `updated_by` varchar(255) DEFAULT NULL,
   `updated_date` datetime DEFAULT NULL,
   `place_of_death` varchar(255) DEFAULT NULL,
   `other_place_of_death` varchar(255) DEFAULT NULL,
   `urine_passed` bit(1) DEFAULT NULL,
   `stool_passed` bit(1) DEFAULT NULL,
   `diarrhoea` bit(1) DEFAULT NULL,
   `vomiting` bit(1) DEFAULT NULL,
   `convulsions` bit(1) DEFAULT NULL,
   `activity` varchar(255) DEFAULT NULL,
   `sucking` varchar(255) DEFAULT NULL,
   `breathing` varchar(255) DEFAULT NULL,
   `chest_indrawing` varchar(255) DEFAULT NULL,
   `temperature` varchar(255) DEFAULT NULL,
   `jaundice` bit(1) DEFAULT NULL,
   `umbilical_stump_condition` varchar(255) DEFAULT NULL,
   `baby_discharged_from_sncu` bit(1) DEFAULT NULL,
   `discharge_summary_image` varchar(255) DEFAULT NULL,
   `hbnc_visit_day` varchar(10) DEFAULT NULL,
   `household_id` mediumtext DEFAULT NULL,
   `date_of_death` varchar(20) DEFAULT NULL,
   `hbnc_due_date` varchar(20) DEFAULT NULL,
   `reason_for_death` varchar(200) DEFAULT NULL ,
   `all_limbs_limp` tinyint(1) DEFAULT 0,
   `baby_cry_continuously` tinyint(1) DEFAULT 0,
   `baby_eyes_swollen` tinyint(1) DEFAULT NULL,
   `baby_fed_properly` tinyint(1) DEFAULT NULL,
   `baby_kept_warm` tinyint(1) DEFAULT NULL,
   `baby_referred` tinyint(1) DEFAULT NULL,
   `baby_temp` float DEFAULT NULL,
   `baby_yellow` tinyint(1) DEFAULT NULL,
   `bloated_stomach` tinyint(1) DEFAULT NULL,
   `breath_fast` tinyint(1) DEFAULT NULL,
   `chest_drawing` tinyint(1) DEFAULT NULL,
   `cold_on_touch` tinyint(1) DEFAULT NULL,
   `crt_weak_stopped` tinyint(1) DEFAULT NULL,
   `baby_referral_date` date DEFAULT NULL,
   `mother_referral_date` date DEFAULT NULL,
   `feeding_less_stopped` tinyint(1) DEFAULT NULL,
   `foul_discharge` tinyint(1) DEFAULT NULL,
   `mother_breast_problem` tinyint(1) DEFAULT NULL,
   `mother_less_no_milk` tinyint(1) DEFAULT NULL,
   `mother_referred` tinyint(1) DEFAULT NULL,
   `mother_speaks_abnormally` tinyint(1) DEFAULT NULL,
   `mother_temp` float DEFAULT NULL,
   `num_pad_changed` int(11) DEFAULT NULL,
   `num_times_full_meal` int(11) DEFAULT NULL,
   `baby_referral_place_other` varchar(255) DEFAULT NULL,
   `mother_referral_place_other` varchar(255) DEFAULT NULL,
   `baby_referral_place` varchar(255) DEFAULT NULL,
   `mother_referral_place` varchar(255) DEFAULT NULL,
   `pus_navel` tinyint(1) DEFAULT NULL,
   `supervisor` varchar(255) DEFAULT NULL,
   `supervisor_comment` text DEFAULT NULL,
   `supervisor_name` varchar(255) DEFAULT NULL,
   `supervisor_sign_date` date DEFAULT NULL,
   `visit_no` int(11) DEFAULT NULL,
   `user_id` int(11) DEFAULT NULL,
   `visit_date` varchar(20) DEFAULT NULL,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `t_hbnc_visit` (
   `id` bigint NOT NULL AUTO_INCREMENT,
   `baby_alive` bit(1) DEFAULT NULL,
   `baby_weight` float DEFAULT NULL,
   `baby_temp` float DEFAULT NULL,
   `baby_yellow` tinyint(1) DEFAULT NULL,
   `baby_cry_continuously` tinyint(1) DEFAULT '0',
   `all_limbs_limp` tinyint(1) DEFAULT '0',
   `baby_fed_properly` tinyint(1) DEFAULT NULL,
   `baby_kept_warm` tinyint(1) DEFAULT NULL,
   `baby_immunization_status` varchar(255) DEFAULT NULL,
   `baby_discharged_from_sncu` bit(1) DEFAULT b'0',
   `discharge_summary_image` varchar(255) DEFAULT NULL,
   `urine_passed` bit(1) DEFAULT NULL,
   `stool_passed` bit(1) DEFAULT NULL,
   `diarrhoea` bit(1) DEFAULT NULL,
   `vomiting` bit(1) DEFAULT NULL,
   `convulsions` bit(1) DEFAULT NULL,
   `activity` varchar(255) DEFAULT NULL,
   `sucking` varchar(255) DEFAULT NULL,
   `breathing` varchar(255) DEFAULT NULL,
   `chest_indrawing` varchar(255) DEFAULT NULL,
   `breath_fast` tinyint(1) DEFAULT NULL,
   `chest_drawing` tinyint(1) DEFAULT NULL,
   `cold_on_touch` tinyint(1) DEFAULT NULL,
   `crt_weak_stopped` tinyint(1) DEFAULT NULL,
   `bloated_stomach` tinyint(1) DEFAULT NULL,
   `jaundice` bit(1) DEFAULT NULL,
   `umbilical_stump_condition` varchar(255) DEFAULT NULL,
   `pus_navel` tinyint(1) DEFAULT NULL,
   `foul_discharge` tinyint(1) DEFAULT NULL,
   `baby_referred` tinyint(1) DEFAULT NULL,
   `baby_referral_date` date DEFAULT NULL,
   `baby_referral_place` varchar(255) DEFAULT NULL,
   `baby_referral_place_other` varchar(255) DEFAULT NULL,
   `mother_referred` tinyint(1) DEFAULT NULL,
   `mother_referral_date` date DEFAULT NULL,
   `mother_referral_place` varchar(255) DEFAULT NULL,
   `mother_referral_place_other` varchar(255) DEFAULT NULL,
   `mother_temp` float DEFAULT NULL,
   `mother_breast_problem` tinyint(1) DEFAULT NULL,
   `mother_less_no_milk` tinyint(1) DEFAULT NULL,
   `mother_speaks_abnormally` tinyint(1) DEFAULT NULL,
   `num_pad_changed` int DEFAULT NULL,
   `num_times_full_meal` int DEFAULT NULL,
   `feeding_less_stopped` tinyint(1) DEFAULT NULL,
   `place_of_death` varchar(255) DEFAULT NULL,
   `other_place_of_death` varchar(255) DEFAULT NULL,
   `date_of_death` varchar(20) DEFAULT NULL,
   `reason_for_death` varchar(200) DEFAULT 'Ttest',
   `hbnc_visit_day` varchar(10) DEFAULT NULL,
   `visit_no` int DEFAULT NULL,
   `visit_date` varchar(20) DEFAULT NULL,
   `hbnc_due_date` varchar(20) DEFAULT NULL,
   `household_id` mediumtext,
   `ben_id` bigint DEFAULT NULL,
   `created_by` varchar(255) DEFAULT NULL,
   `created_date` datetime DEFAULT NULL,
   `updated_by` varchar(255) DEFAULT NULL,
   `updated_date` datetime DEFAULT NULL,
   `supervisor` varchar(255) DEFAULT NULL,
   `supervisor_name` varchar(255) DEFAULT NULL,
   `supervisor_comment` text,
   `supervisor_sign_date` date DEFAULT NULL,
   `temperature` varchar(20) DEFAULT NULL,
   `asha_id` int DEFAULT NULL,
   `baby_eyes_swollen` tinyint(1) DEFAULT NULL,
   PRIMARY KEY (`id`)
 ) ENGINE=InnoDB AUTO_INCREMENT=103 DEFAULT CHARSET=utf8mb3;