
ALTER TABLE t_pmsma 
ADD COLUMN IF NOT EXISTS visitDate DATETIME NULL;

ALTER TABLE t_pmsma 
ADD COLUMN IF NOT EXISTS visitNo SMALLINT NULL;

ALTER TABLE t_pmsma 
ADD COLUMN IF NOT EXISTS anyOtherHighRiskCondition VARCHAR(100) NULL;
