USE db_iemr;

-- ===============================================
--  Table: t_hbnc_visit
-- ===============================================
CREATE TABLE IF NOT EXISTS `t_hbnc_visit` (
   `id` bigint NOT NULL AUTO_INCREMENT,
   `all_limbs_limp` bit(1) DEFAULT NULL,
   `baby_alive` bit(1) DEFAULT NULL,
   `baby_cry_continuously` bit(1) DEFAULT NULL,
   `baby_eyes_swollen` bit(1) DEFAULT NULL,
   `baby_fed_properly` bit(1) DEFAULT NULL,
   `baby_immunization_status` varchar(255) DEFAULT NULL,
   `baby_kept_warm` bit(1) DEFAULT NULL,
   `baby_referred` bit(1) DEFAULT NULL,
   `baby_temp` int DEFAULT NULL,
   `baby_weight` float DEFAULT NULL,
   `baby_yellow` bit(1) DEFAULT NULL,
   `ben_id` bigint DEFAULT NULL,
   `bloated_stomach` bit(1) DEFAULT NULL,
   `breath_fast` bit(1) DEFAULT NULL,
   `chest_drawing` bit(1) DEFAULT NULL,
   `cold_on_touch` bit(1) DEFAULT NULL,
   `created_by` varchar(255) DEFAULT NULL,
   `created_date` datetime DEFAULT NULL,
   `crt_weak_stopped` bit(1) DEFAULT NULL,
   `baby_referral_date` datetime DEFAULT NULL,
   `mother_referral_date` datetime DEFAULT NULL,
   `visit_date` datetime DEFAULT NULL,
   `feeding_less_stopped` bit(1) DEFAULT NULL,
   `foul_discharge` bit(1) DEFAULT NULL,
   `mother_breast_problem` bit(1) DEFAULT NULL,
   `mother_less_no_milk` bit(1) DEFAULT NULL,
   `mother_referred` bit(1) DEFAULT NULL,
   `mother_speaks_abnormally` bit(1) DEFAULT NULL,
   `mother_temp` int DEFAULT NULL,
   `num_pad_changed` int DEFAULT NULL,
   `num_times_full_meal` int DEFAULT NULL,
   `baby_referral_place_other` varchar(255) DEFAULT NULL,
   `mother_referral_place_other` varchar(255) DEFAULT NULL,
   `baby_referral_place` varchar(255) DEFAULT NULL,
   `mother_referral_place` varchar(255) DEFAULT NULL,
   `pus_navel` varchar(255) DEFAULT NULL,
   `supervisor` varchar(255) DEFAULT NULL,
   `supervisor_comment` varchar(255) DEFAULT NULL,
   `supervisor_name` varchar(255) DEFAULT NULL,
   `supervisor_sign_date` datetime DEFAULT NULL,
   `updated_by` varchar(255) DEFAULT NULL,
   `updated_date` datetime DEFAULT NULL,
   `visit_no` int DEFAULT NULL,
   PRIMARY KEY (`id`)
 ) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb3;
