CREATE TABLE IF NOT EXISTS `db_iemr`.`leprosy_follow_up` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ben_id` BIGINT DEFAULT NULL,
  `visit_number` INT DEFAULT NULL,
  `follow_up_date` DATE DEFAULT NULL,
  `treatment_status` VARCHAR(100) DEFAULT NULL,
  `mdt_blister_pack_received` VARCHAR(100) DEFAULT NULL,
  `treatment_complete_date` DATE DEFAULT NULL,
  `remarks` TEXT DEFAULT NULL,
  `home_visit_date` DATE DEFAULT NULL,
  `leprosy_symptoms` VARCHAR(255) DEFAULT NULL,
  `type_of_leprosy` VARCHAR(100) DEFAULT NULL,
  `leprosy_symptoms_position` INT DEFAULT NULL,
  `visit_label` VARCHAR(100) DEFAULT NULL,
  `leprosy_status` VARCHAR(100) DEFAULT NULL,
  `referred_to` VARCHAR(255) DEFAULT NULL,
  `refer_to_name` VARCHAR(255) DEFAULT NULL,
  `treatment_end_date` DATE DEFAULT NULL,
  `mdt_blister_pack_recived` VARCHAR(100) DEFAULT NULL,
  `treatment_start_date` DATE DEFAULT NULL,
  `created_by` VARCHAR(100) DEFAULT NULL,
  `created_date` TIMESTAMP NULL DEFAULT NULL,
  `modified_by` VARCHAR(100) DEFAULT NULL,
  `last_mod_date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
)