USE db_iemr;

ALTER TABLE t_anc_visit
ADD COLUMN IF NOT EXISTS file_path VARCHAR(255),
ADD COLUMN IF NOT EXISTS serial_no VARCHAR(100),

ADD COLUMN IF NOT EXISTS method_of_termination VARCHAR(100),
ADD COLUMN IF NOT EXISTS method_of_termination_id INT,

ADD COLUMN IF NOT EXISTS termination_done_by VARCHAR(100),
ADD COLUMN IF NOT EXISTS termination_done_by_id INT,

ADD COLUMN IF NOT EXISTS is_paiucd_id INT,
ADD COLUMN IF NOT EXISTS is_paiucd VARCHAR(10),

ADD COLUMN IF NOT EXISTS remarks TEXT,

ADD COLUMN IF NOT EXISTS abortion_img1 VARCHAR(255),
ADD COLUMN IF NOT EXISTS abortion_img2 VARCHAR(255),

ADD COLUMN IF NOT EXISTS place_of_death VARCHAR(100),
ADD COLUMN IF NOT EXISTS place_of_death_id INT,
ADD COLUMN IF NOT EXISTS other_place_of_death VARCHAR(255),

ADD COLUMN IF NOT EXISTS visit_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS lmp_date TIMESTAMP,

ADD COLUMN IF NOT EXISTS is_YesOrNo BOOLEAN,

ADD COLUMN IF NOT EXISTS date_of_sterilisation TIMESTAMP,

ADD COLUMN IF NOT EXISTS place_of_anc VARCHAR(100),
ADD COLUMN IF NOT EXISTS place_of_ancId INT;
