USE db_iemr;
CREATE TABLE IF NOT EXISTS `t_hbyc_child_visits` (
   `id` bigint NOT NULL AUTO_INCREMENT,
   `beneficiary_id` bigint DEFAULT NULL,
   `household_id` bigint DEFAULT NULL,
   `visit_day` varchar(50) DEFAULT NULL,
   `user_id` int DEFAULT NULL,
   `hbyc_due_date` DATE DEFAULT NULL,
   `hbyc_visit_date` DATE DEFAULT NULL,
   `is_baby_alive` tinyint(1) DEFAULT 1,
   `date_of_death` DATE DEFAULT NULL,
   `reason_for_death` varchar(255) DEFAULT NULL,
   `place_of_death` varchar(255) DEFAULT NULL,
   `other_place_of_death` varchar(255) DEFAULT NULL,
   `baby_weight` decimal(4,2) DEFAULT NULL,
   `is_child_sick` tinyint(1) DEFAULT NULL,
   `is_exclusive_breastfeeding` tinyint(1) DEFAULT NULL,
   `is_mother_counseled_exbf` tinyint(1) DEFAULT NULL,
   `has_child_started_complementary_feeding` tinyint(1) DEFAULT NULL,
   `is_mother_counseled_cf` tinyint(1) DEFAULT NULL,
   `is_weight_recorded_by_aww` tinyint(1) DEFAULT NULL,
   `is_developmental_delay` tinyint(1) DEFAULT NULL,
   `is_measles_vaccine_given` tinyint(1) DEFAULT NULL,
   `is_vitamin_a_given` tinyint(1) DEFAULT NULL,
   `is_ors_available` tinyint(1) DEFAULT NULL,
   `is_ifa_syrup_available` tinyint(1) DEFAULT NULL,
   `is_ors_given` tinyint(1) DEFAULT NULL,
   `is_ifa_syrup_given` tinyint(1) DEFAULT NULL,
   `is_handwashing_counseling_given` tinyint(1) DEFAULT NULL,
   `is_parenting_counseling_given` tinyint(1) DEFAULT NULL,
   `is_family_planning_counseling_given` tinyint(1) DEFAULT NULL,
   `diarrhoea_episode` tinyint(1) DEFAULT NULL,
   `pneumonia_symptoms` tinyint(1) DEFAULT NULL,
   `temperature` decimal(4,2) DEFAULT NULL,
   `mcp_card_images` json DEFAULT NULL,
   `created_date` datetime DEFAULT CURRENT_TIMESTAMP,
   `updated_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   `created_by` varchar(100) DEFAULT NULL,
   `is_breathing_difficulty` tinyint(1) DEFAULT NULL,
   `is_complementary_feeding` tinyint(1) DEFAULT NULL,
   PRIMARY KEY (`id`),
   KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
