use db_iemr;

CREATE TABLE `t_videocallparameter` (
  `MeetingID` INT(11) NOT NULL AUTO_INCREMENT,
  `DateOfCall` TIMESTAMP DEFAULT NULL,
  `CallerPhoneNumber` VARCHAR(255) DEFAULT NULL,
  `AgentID` VARCHAR(255) DEFAULT NULL,
  `AgentName` VARCHAR(255) DEFAULT NULL,
  `MeetingLink` VARCHAR(255) DEFAULT NULL,
  `CallStatus` VARCHAR(255) DEFAULT NULL,
  `CallDuration` VARCHAR(255) DEFAULT NULL,
  `ProviderServiceMapID` INT(11) DEFAULT NULL,
  `BeneficiaryRegID` bigint(20) DEFAULT NULL,
  `ClosureRemark` TEXT DEFAULT NULL,
  `Deleted` BOOLEAN DEFAULT FALSE,
  `LinkGeneratedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `IsLinkUsed` TINYINT(1) DEFAULT 0,
  `CreatedBy` VARCHAR(255) DEFAULT NULL,
  `CreatedDate` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `ModifiedBy` VARCHAR(255) DEFAULT NULL,
  `LastModDate` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`MeetingID`)
);
