USE db_iemr;

CREATE TABLE IF NOT EXISTS `oral_health` (
   `id` bigint NOT NULL AUTO_INCREMENT,
   `patient_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
   `ben_visit_no` int DEFAULT NULL,
   `tooth_decay_present` tinyint(1) DEFAULT NULL,
   `tooth_decay_symptoms` text COLLATE utf8mb4_unicode_ci,
   `gum_disease_present` tinyint(1) DEFAULT NULL,
   `gum_disease_symptoms` text COLLATE utf8mb4_unicode_ci,
   `irregular_teeth_jaws` tinyint(1) DEFAULT NULL,
   `abnormal_growth_ulcer` tinyint(1) DEFAULT NULL,
   `cleft_lip_palate` tinyint(1) DEFAULT NULL,
   `dental_fluorosis` tinyint(1) DEFAULT NULL,
   `dental_emergency` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `created_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `user_id` int DEFAULT NULL,
   `updated_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `created_date` mediumtext COLLATE utf8mb4_unicode_ci,
   `updated_date` mediumtext COLLATE utf8mb4_unicode_ci,
   `beneficiary_id` bigint DEFAULT NULL,
   `beneficiary_reg_id` bigint DEFAULT NULL,
   PRIMARY KEY (`id`),
   UNIQUE KEY `uq_oral_health_patient_visit` (`patient_id`,`ben_visit_no`),
   KEY `idx_oh_user_id` (`user_id`)
);

CREATE TABLE IF NOT EXISTS `pain_symptom_assessment` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `patient_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
    `ben_visit_no` int DEFAULT NULL,
    `pain_severity` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `pain_duration` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `symptoms_present` tinyint(1) DEFAULT NULL,
    `other_symptoms_severity` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `immediate_relief_provided` tinyint(1) DEFAULT NULL,
    `persistent_pain_present` tinyint(1) DEFAULT NULL,
    `pain_assessment_enabled` tinyint(1) DEFAULT NULL,
    `distressing_symptoms_present` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `bedridden_or_severely_dependent` tinyint(1) DEFAULT NULL,
    `life_limiting_illness_known` tinyint(1) DEFAULT NULL,
    `caregiver_support_required` tinyint(1) DEFAULT NULL,
    `palliative_care_eligible` tinyint(1) DEFAULT NULL,
    `referral_required` tinyint(1) DEFAULT NULL,
    `referral_level` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `reason_for_referral` text COLLATE utf8mb4_unicode_ci,
    `follow_up_required` tinyint(1) DEFAULT NULL,
    `follow_up_date` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `case_status` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `date_of_death` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `remarks` text COLLATE utf8mb4_unicode_ci,
    `created_date` bigint DEFAULT NULL COMMENT 'epoch ms',
    `created_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `updated_date` bigint DEFAULT NULL COMMENT 'epoch ms',
    `updated_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `beneficiary_id` mediumtext COLLATE utf8mb4_unicode_ci,
    `user_id` int DEFAULT NULL,
    `beneficiary_reg_id` mediumtext COLLATE utf8mb4_unicode_ci,
    PRIMARY KEY (`id`),
    KEY `idx_psa_user_id` (`user_id`)
);

CREATE TABLE IF NOT EXISTS `psychosocial_caregiver_support` (
     `id` bigint NOT NULL AUTO_INCREMENT,
     `patient_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
     `ben_visit_no` int DEFAULT NULL,
     `psychosocial_counselling_provided` tinyint(1) DEFAULT NULL,
     `caregiver_counselling_provided` tinyint(1) DEFAULT NULL,
     `caregiver_distress_identified` tinyint(1) DEFAULT NULL,
     `counselling_remarks` text COLLATE utf8mb4_unicode_ci,
     `referral_required` tinyint(1) DEFAULT NULL,
     `referral_level` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
     `reason_for_referral` text COLLATE utf8mb4_unicode_ci,
     `follow_up_required` tinyint(1) DEFAULT NULL,
     `follow_up_date` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
     `case_status` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
     `date_of_death` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
     `remarks` text COLLATE utf8mb4_unicode_ci,
     `created_date` bigint DEFAULT NULL COMMENT 'epoch ms',
     `created_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
     `updated_date` bigint DEFAULT NULL COMMENT 'epoch ms',
     `updated_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
     `user_id` int DEFAULT NULL,
     `beneficiary_id` bigint DEFAULT NULL,
     `beneficiary_reg_id` bigint DEFAULT NULL,
     PRIMARY KEY (`id`),
     KEY `idx_pcs_user_id` (`user_id`)
);

CREATE TABLE IF NOT EXISTS `nose_diagnosis_assessment` (
   `id` bigint NOT NULL AUTO_INCREMENT,
   `patient_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
   `ben_visit_no` int DEFAULT NULL,
   `difficulty_breathing` tinyint(1) DEFAULT NULL,
   `open_mouth_breathing` tinyint(1) DEFAULT NULL,
   `nose_bleed` tinyint(1) DEFAULT NULL,
   `systolic_bp` int DEFAULT NULL,
   `diastolic_bp` int DEFAULT NULL,
   `foreign_body_nose` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `sinusitis` tinyint(1) DEFAULT NULL,
   `created_date` bigint DEFAULT NULL COMMENT 'epoch ms',
   `created_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `updated_date` bigint DEFAULT NULL COMMENT 'epoch ms',
   `updated_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `user_id` int DEFAULT NULL,
   `beneficiary_id` bigint DEFAULT NULL,
   `beneficiary_reg_id` bigint DEFAULT NULL,
   PRIMARY KEY (`id`),
   KEY `idx_nda_user_id` (`user_id`)
);

CREATE TABLE IF NOT EXISTS `throat_diagnosis_assessment` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `patient_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
    `ben_visit_no` int DEFAULT NULL,
    `symptoms` text COLLATE utf8mb4_unicode_ci COMMENT 'JSON array',
    `neck_swelling` tinyint(1) DEFAULT NULL,
    `difficulty_swallowing` tinyint(1) DEFAULT NULL,
    `tonsillitis` tinyint(1) DEFAULT NULL,
    `pharyngitis` tinyint(1) DEFAULT NULL,
    `laryngitis` tinyint(1) DEFAULT NULL,
    `sinusitis` tinyint(1) DEFAULT NULL,
    `cleft_lip` tinyint(1) DEFAULT NULL,
    `cleft_palate` tinyint(1) DEFAULT NULL,
    `created_date` bigint DEFAULT NULL COMMENT 'epoch ms',
    `created_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `updated_date` bigint DEFAULT NULL COMMENT 'epoch ms',
    `updated_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `user_id` int DEFAULT NULL,
    `beneficiary_id` bigint DEFAULT NULL,
    `beneficiary_reg_id` bigint DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_tda_user_id` (`user_id`)
);

CREATE TABLE IF NOT EXISTS `opthalmic_visit` (
     `visitId` varchar(36) NOT NULL COMMENT 'UUID',
     `patientID` varchar(36) NOT NULL COMMENT 'FK → Patient',
     `benVisitNo` int NOT NULL,
     `isDiabetic` tinyint(1) DEFAULT NULL,
     `screeningPerformed` tinyint(1) DEFAULT NULL,
     `visualAcuityChartUsed` varchar(100) DEFAULT NULL,
     `distVARight` varchar(50) DEFAULT NULL,
     `distVALeft` varchar(50) DEFAULT NULL,
     `nearVA` varchar(50) DEFAULT NULL,
     `caseIdConditions` text COMMENT 'JSON',
     `cataractSymptoms` tinyint(1) DEFAULT NULL,
     `glaucomaSymptoms` tinyint(1) DEFAULT NULL,
     `diabeticRetinopathySymptoms` tinyint(1) DEFAULT NULL,
     `presbyopiaSymptoms` tinyint(1) DEFAULT NULL,
     `trachomaStatus` varchar(100) DEFAULT NULL,
     `cornealDiseaseType` varchar(100) DEFAULT NULL,
     `vitaminADeficiency` tinyint(1) DEFAULT NULL,
     `injuryType` text COMMENT 'JSON',
     `foreignBodyRemoval` varchar(255) DEFAULT NULL,
     `chemicalExposure` tinyint(1) DEFAULT NULL,
     `createdBy` varchar(100) NOT NULL,
     `createdDate` bigint NOT NULL COMMENT 'epoch ms',
     `updatedBy` varchar(100) NOT NULL,
     `updatedDate` bigint NOT NULL COMMENT 'epoch ms',
     `syncState` int NOT NULL DEFAULT '0' COMMENT 'Internal sync flag',
     `beneficiary_id` mediumtext,
     `user_id` int DEFAULT NULL,
     `beneficiary_reg_id` mediumtext,
     PRIMARY KEY (`visitId`),
     KEY `idx_ophthalmic_patientID` (`patientID`),
     KEY `idx_ov_user_id` (`user_id`)
);

CREATE TABLE IF NOT EXISTS `ear_diagnosis_assessment` (
      `assessment_id` int NOT NULL AUTO_INCREMENT,
      `patient_id` varchar(36) NOT NULL,
      `ben_visit_no` int DEFAULT NULL,
      `difficulty_hearing` tinyint(1) DEFAULT NULL,
      `whisper_test_response` varchar(100) DEFAULT NULL,
      `hearing_test_outcome` varchar(100) DEFAULT NULL,
      `ear_pain` tinyint(1) DEFAULT NULL,
      `ear_discharge_present` tinyint(1) DEFAULT NULL,
      `foreign_body_in_ear` varchar(255) DEFAULT NULL,
      `ear_condition_type` varchar(100) DEFAULT NULL,
      `congenital_ear_malformation` tinyint(1) DEFAULT NULL,
      `user_id` int DEFAULT NULL,
      `beneficiary_id` mediumtext,
      `beneficiary_reg_id` mediumtext,
      PRIMARY KEY (`assessment_id`),
      KEY `idx_eda_user_id` (`user_id`)
);

CREATE TABLE IF NOT EXISTS `elderly_health_assessment` (
       `id` bigint NOT NULL AUTO_INCREMENT,
       `patient_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
       `ben_visit_no` int NOT NULL,
       `geriatric_complaints` tinyint(1) DEFAULT NULL,
       `multiple_chronic_conditions` tinyint(1) DEFAULT NULL,
       `recent_falls` tinyint(1) DEFAULT NULL,
       `difficulty_walking_balance` tinyint(1) DEFAULT NULL,
       `visual_hearing_difficulty` tinyint(1) DEFAULT NULL,
       `functional_decline` tinyint(1) DEFAULT NULL,
       `memory_loss` tinyint(1) DEFAULT NULL,
       `dementia_memory_loss` tinyint(1) DEFAULT NULL,
       `dementia_disorientation` tinyint(1) DEFAULT NULL,
       `dementia_behavioural_changes` tinyint(1) DEFAULT NULL,
       `dementia_self_care_decline` tinyint(1) DEFAULT NULL,
       `dementia_screening_outcome` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
       `dementia_referral_required` tinyint(1) DEFAULT NULL,
       `referral_required` tinyint(1) DEFAULT NULL,
       `referral_level` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
       `reason_for_referral` text COLLATE utf8mb4_unicode_ci,
       `follow_up_required` tinyint(1) DEFAULT NULL,
       `follow_up_date` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
       `case_status` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
       `date_of_death` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
       `remarks` text COLLATE utf8mb4_unicode_ci,
       `user_id` int DEFAULT NULL,
       `beneficiary_id` bigint DEFAULT NULL,
       `beneficiary_reg_id` bigint DEFAULT NULL,
       `bathing` int DEFAULT NULL,
       `dressing` int DEFAULT NULL,
       `toileting` int DEFAULT NULL,
       `transferring` int DEFAULT NULL,
       `continence` int DEFAULT NULL,
       `feeding` int DEFAULT NULL,
       `total_score` int DEFAULT NULL,
       `functional_status` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
       `functional_decline_flag` tinyint(1) DEFAULT NULL,
       PRIMARY KEY (`id`),
       UNIQUE KEY `uq_elderly_patient_visit` (`patient_id`,`ben_visit_no`),
       KEY `idx_eha_user_id` (`user_id`)
);

CREATE TABLE IF NOT EXISTS `mental_health_screening` (
        `id` bigint NOT NULL AUTO_INCREMENT,
        `patient_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
        `ben_visit_no` int DEFAULT NULL,
        `emotional_behavioural_concerns` tinyint(1) DEFAULT NULL,
        `substance_use_concerns` tinyint(1) DEFAULT NULL,
        `self_harm_suicide_thoughts` tinyint(1) DEFAULT NULL,
        `memory_loss_confusion` tinyint(1) DEFAULT NULL,
        `seizures_fits_loc` tinyint(1) DEFAULT NULL,
        `is_postpartum` tinyint(1) DEFAULT NULL,
        `phq9_little_interest` int DEFAULT NULL,
        `phq9_feeling_down` int DEFAULT NULL,
        `phq9_sleep_trouble` int DEFAULT NULL,
        `phq9_feeling_tired` int DEFAULT NULL,
        `phq9_appetite` int DEFAULT NULL,
        `phq9_feeling_bad` int DEFAULT NULL,
        `phq9_concentration` int DEFAULT NULL,
        `phq9_moving_slowly` int DEFAULT NULL,
        `phq9_self_harm_thoughts` int DEFAULT NULL,
        `phq9_total_score` int DEFAULT NULL,
        `phq9_depression_severity` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `phq9_system_action` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `substance_current_tobacco_use` tinyint(1) DEFAULT NULL,
        `substance_tobacco_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `substance_tobacco_frequency` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `substance_tobacco_outcome` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `substance_system_action` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `substance_alcohol_use` tinyint(1) DEFAULT NULL,
        `substance_tobacco_use` tinyint(1) DEFAULT NULL,
        `substance_other_use` tinyint(1) DEFAULT NULL,
        `substance_other_specify` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `substance_frequency` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `brief_intervention_given` tinyint(1) DEFAULT NULL,
        `substance_alcohol_impact` tinyint(1) DEFAULT NULL,
        `substance_alcohol_withdrawal` tinyint(1) DEFAULT NULL,
        `substance_alcohol_problematic` tinyint(1) DEFAULT NULL,
        `substance_alcohol_classification` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `substance_alcohol_system_action` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `substance_alcohol_frequency` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `substance_alcohol_loss` tinyint(1) DEFAULT NULL,
        `suicide_current_thoughts` tinyint(1) DEFAULT NULL,
        `suicide_plan` tinyint(1) DEFAULT NULL,
        `suicide_previous_attempt` tinyint(1) DEFAULT NULL,
        `suicide_hopelessness` tinyint(1) DEFAULT NULL,
        `suicide_immediate_assess` tinyint(1) DEFAULT NULL,
        `suicide_risk_level` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `dementia_progressive_memory_loss` tinyint(1) DEFAULT NULL,
        `dementia_forgetting_recent` tinyint(1) DEFAULT NULL,
        `dementia_disorientation` tinyint(1) DEFAULT NULL,
        `dementia_daily_activities` tinyint(1) DEFAULT NULL,
        `dementia_behavioural_changes` tinyint(1) DEFAULT NULL,
        `epilepsy_recurrent_seizures` tinyint(1) DEFAULT NULL,
        `epilepsy_jerky_movements` tinyint(1) DEFAULT NULL,
        `epilepsy_tongue_bite` tinyint(1) DEFAULT NULL,
        `epilepsy_confusion_after` tinyint(1) DEFAULT NULL,
        `epilepsy_loc_duration` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `edRecurrentEpisodeloss` tinyint(1) DEFAULT NULL,
        `ed_recurrent_jerky_movements` tinyint(1) DEFAULT NULL,
        `ed_progressive_memory_loss` tinyint(1) DEFAULT NULL,
        `ed_confusion_disorientation` tinyint(1) DEFAULT NULL,
        `ed_functional_decline` tinyint(1) DEFAULT NULL,
        `ed_screening_outcome` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `ed_psychosocial_intervention_provided` tinyint(1) DEFAULT NULL,
        `ed_intervention_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `ed_session_date` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `ed_duration_minutes` int DEFAULT NULL,
        `ed_remarks` text COLLATE utf8mb4_unicode_ci,
        `ed_referral_required` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `referral_required` tinyint(1) DEFAULT NULL,
        `referral_level` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `reason_for_referral` text COLLATE utf8mb4_unicode_ci,
        `referral_date` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `follow_up_required` tinyint(1) DEFAULT NULL,
        `follow_up_date` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `improvement_noted` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `referral_escalation_required` tinyint(1) DEFAULT NULL,
        `case_closure_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        `user_id` int DEFAULT NULL,
        `beneficiary_id` bigint DEFAULT NULL,
        `beneficiary_reg_id` bigint DEFAULT NULL,
        PRIMARY KEY (`id`),
        KEY `idx_mhs_patient_id` (`patient_id`),
        KEY `idx_mhs_patient_visit` (`patient_id`,`ben_visit_no`),
        KEY `idx_mhs_user_id` (`user_id`)
);