USE db_iemr;

-- ─────────────────────────────────────────────────────────────
-- StopTB dual-write tables. CREATE TABLE IF NOT EXISTS — safe to
-- run on any environment, whether these already exist (no-op) or
-- this is a fresh install. Dynamic Form tables are a separate,
-- already-existing migration (V87__Dynamic_Form_Module.sql) —
-- not duplicated here.
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS `tb_stoptb_general_examination` (
  `id`                              BIGINT       NOT NULL AUTO_INCREMENT,
  `beneficiary_reg_id`              BIGINT       DEFAULT NULL,
  `provider_service_map_id`         INT          DEFAULT NULL,
  `pulse_rate`                      INT          DEFAULT NULL,
  `systolic_bp`                     INT          DEFAULT NULL,
  `diastolic_bp`                    INT          DEFAULT NULL,
  `random_blood_sugar`              DOUBLE       DEFAULT NULL,
  `pallor_id`                       INT          DEFAULT NULL,
  `pallor`                          VARCHAR(255) DEFAULT NULL,
  `icterus_id`                      INT          DEFAULT NULL,
  `icterus`                         VARCHAR(255) DEFAULT NULL,
  `lymphadenopathy_id`              INT          DEFAULT NULL,
  `lymphadenopathy`                 VARCHAR(255) DEFAULT NULL,
  `oedema_id`                       INT          DEFAULT NULL,
  `oedema`                          VARCHAR(255) DEFAULT NULL,
  `cyanosis_id`                     INT          DEFAULT NULL,
  `cyanosis`                        VARCHAR(255) DEFAULT NULL,
  `clubbing_id`                     INT          DEFAULT NULL,
  `clubbing`                        VARCHAR(255) DEFAULT NULL,
  `key_population_risk_factor_ids`  TEXT         DEFAULT NULL,
  `key_population_risk_factors`     TEXT         DEFAULT NULL,
  `hiv_status_id`                   INT          DEFAULT NULL,
  `hiv_status`                      VARCHAR(255) DEFAULT NULL,
  `referral_to_hwc_needed_id`       INT          DEFAULT NULL,
  `referral_to_hwc_needed`          TINYINT(1)   DEFAULT NULL,
  `created_by`                      VARCHAR(255) DEFAULT NULL,
  `created_date`                    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_by`                     VARCHAR(100) DEFAULT NULL,
  `last_mod_date`                   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`                         TINYINT(1)   DEFAULT 0,
  `vanID`                           INT          DEFAULT NULL,
  `parkingPlaceID`                  INT          DEFAULT NULL,
  `visitCode`                       BIGINT       DEFAULT NULL,
  `processed`                       VARCHAR(1)   DEFAULT 'N',
  `vanSerialNo`                     BIGINT       DEFAULT NULL,
  `benVisitID`                      BIGINT       DEFAULT NULL,
  `ben_id`                          BIGINT       DEFAULT NULL,
  `SyncedDate`                      DATETIME     DEFAULT NULL,
  `Syncedby`                        VARCHAR(50)  DEFAULT NULL,
  `SyncFailureReason`               VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sync_tb_gen_exam` (`vanID`, `processed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tb_stoptb_general_opd` (
  `id`                      BIGINT       NOT NULL AUTO_INCREMENT,
  `ben_reg_id`              BIGINT       DEFAULT NULL,
  `provider_service_map_id` INT          DEFAULT NULL,
  `chief_complaint`         TEXT         DEFAULT NULL,
  `medication`              TEXT         DEFAULT NULL,
  `dosage`                  VARCHAR(255) DEFAULT NULL,
  `frequency`               VARCHAR(255) DEFAULT NULL,
  `duration`                VARCHAR(255) DEFAULT NULL,
  `notes`                   TEXT         DEFAULT NULL,
  `created_by`              VARCHAR(255) DEFAULT NULL,
  `created_date`            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_by`             VARCHAR(50)  DEFAULT NULL,
  `last_mod_date`           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`                 TINYINT(1)   DEFAULT 0,
  `vanID`                   INT          DEFAULT NULL,
  `parkingPlaceID`          INT          DEFAULT NULL,
  `visitCode`               BIGINT       DEFAULT NULL,
  `processed`               VARCHAR(1)   DEFAULT 'N',
  `vanSerialNo`             BIGINT       DEFAULT NULL,
  `benVisitID`              BIGINT       DEFAULT NULL,
  `SyncedDate`              DATETIME     DEFAULT NULL,
  `Syncedby`                VARCHAR(50)  DEFAULT NULL,
  `SyncFailureReason`       VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sync_tb_gen_opd` (`vanID`, `processed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tb_stoptb_diagnostics` (
  `id`                                    BIGINT       NOT NULL AUTO_INCREMENT,
  `ben_reg_id`                            BIGINT       DEFAULT NULL,
  `provider_service_map_id`               INT          DEFAULT NULL,
  `visit_date`                            TIMESTAMP    NULL DEFAULT NULL,
  `nikshay_id`                            VARCHAR(50)  DEFAULT NULL,
  `is_referred_for_digital_chest_xray`    TINYINT(1)   DEFAULT NULL,
  `reason_for_denial_chest_xray`          VARCHAR(255) DEFAULT NULL,
  `reason_for_denial_chest_xray_other`    VARCHAR(255) DEFAULT NULL,
  `is_digital_chest_xray_conducted_id`    INT          DEFAULT NULL,
  `is_digital_chest_xray_conducted`       TINYINT(1)   DEFAULT NULL,
  `reason_not_conducted_chest_xray`       VARCHAR(255) DEFAULT NULL,
  `reason_not_conducted_chest_xray_other` VARCHAR(255) DEFAULT NULL,
  `digital_chest_xray_result_id`          INT          DEFAULT NULL,
  `digital_chest_xray_result`             VARCHAR(20)  DEFAULT NULL,
  `is_referred_for_sputum_collection`     TINYINT(1)   DEFAULT NULL,
  `reason_for_denial_sputum`              VARCHAR(500) DEFAULT NULL,
  `reason_for_denial_sputum_other`        VARCHAR(255) DEFAULT NULL,
  `sputum_submitted_at`                   VARCHAR(255) DEFAULT NULL,
  `is_truenat_conducted_id`               INT          DEFAULT NULL,
  `is_truenat_conducted`                  TINYINT(1)   DEFAULT NULL,
  `reason_not_conducted_naat`             VARCHAR(255) DEFAULT NULL,
  `reason_not_conducted_naat_other`       VARCHAR(255) DEFAULT NULL,
  `truenat_result_id`                     INT          DEFAULT NULL,
  `truenat_result`                        VARCHAR(20)  DEFAULT NULL,
  `recommended_for_liquid_culture_id`     INT          DEFAULT NULL,
  `recommended_for_liquid_culture`        TINYINT(1)   DEFAULT NULL,
  `liquid_culture_result_id`              INT          DEFAULT NULL,
  `liquid_culture_result`                 VARCHAR(20)  DEFAULT NULL,
  `created_by`                            VARCHAR(255) DEFAULT NULL,
  `created_date`                          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_by`                           VARCHAR(255) DEFAULT NULL,
  `last_mod_date`                         DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`                               TINYINT(1)   DEFAULT 0,
  `vanID`                                 INT          DEFAULT NULL,
  `parkingPlaceID`                        INT          DEFAULT NULL,
  `visitCode`                             BIGINT       DEFAULT NULL,
  `processed`                             VARCHAR(1)   DEFAULT 'N',
  `vanSerialNo`                           BIGINT       DEFAULT NULL,
  `SyncedDate`                            DATETIME     DEFAULT NULL,
  `Syncedby`                              VARCHAR(50)  DEFAULT NULL,
  `SyncFailureReason`                     VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sync_tb_diag` (`vanID`, `processed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
