use db_identity;
-- add  beneficiary death column
ALTER TABLE i_beneficiarydetails_rmnch
ADD COLUMN IF NOT EXISTS isDeath TINYINT(1) DEFAULT 0 ;
ADD COLUMN IF NOT EXISTS isDeathValue VARCHAR(50) DEFAULT NULL ;
ADD COLUMN IF NOT EXISTS timeOfDeath VARCHAR(20) DEFAULT NULL ;
ADD COLUMN IF NOT EXISTS reasonOfDeath VARCHAR(255) DEFAULT NULL ;
ADD COLUMN IF NOT EXISTS reasonOfDeathId INT DEFAULT NULL ;
ADD COLUMN IF NOT EXISTS placeOfDeath VARCHAR(255) DEFAULT NULl;
ADD COLUMN IF NOT EXISTS IF NOT EXISTS placeOfDeathId INT DEFAULT NULL;
ADD COLUMN IF NOT EXISTS otherPlaceOfDeath VARCHAR(255) DEFAULT;
ADD COLUMN IF NOT EXISTS dateOfDeath VARCHAR(200) DEFAULT NULL;
