use db_identity;
-- add  beneficiary death column
ALTER TABLE i_beneficiarydetails_rmnch
ADD COLUMN isDeath TINYINT(1) DEFAULT 0 ;
ADD COLUMN isDeathValue VARCHAR(50) DEFAULT NULL ;
ADD COLUMN timeOfDeath VARCHAR(20) DEFAULT NULL ;
ADD COLUMN reasonOfDeath VARCHAR(255) DEFAULT NULL ;
ADD COLUMN reasonOfDeathId INT DEFAULT NULL ;
ADD COLUMN placeOfDeath VARCHAR(255) DEFAULT NULl;
ADD COLUMN placeOfDeathId INT DEFAULT NULL;
ADD COLUMN otherPlaceOfDeath VARCHAR(255) DEFAULT;
ADD COLUMN dateOfDeath VARCHAR(200) DEFAULT NULL;