CREATE TABLE `t_elasticsearch_sync_job` (
  `job_id` bigint NOT NULL AUTO_INCREMENT,
  `job_type` varchar(50) NOT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'PENDING',
  `total_records` bigint DEFAULT '0',
  `processed_records` bigint DEFAULT '0',
  `success_count` bigint DEFAULT '0',
  `failure_count` bigint DEFAULT '0',
  `current_offset` int DEFAULT '0',
  `started_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `error_message` text,
  `triggered_by` varchar(100) DEFAULT NULL,
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `estimated_time_remaining` bigint DEFAULT NULL,
  `processing_speed` double DEFAULT NULL,
  PRIMARY KEY (`job_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_date` (`created_date`),
  KEY `idx_job_type` (`job_type`)
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci