name: CodeQL
on:
  push:
    branches: [ "main","develop" ]
    paths-ignore:
     - target/**
     
  pull_request:
    branches: [ "main","develop" ]
    paths-ignore:
     - target/**

jobs:
  analyze:
    name: Analyze
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
       
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
          java-version: 17
          distribution: 'adopt'
       
    - name: Build with Maven
      run: mvn clean install -Dmaven.test.skip=true

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
